-- Facility / room data table for CSV import
-- IMPORTANT: Column names must match your CSV header row EXACTLY.
-- Open your CSV in Notepad and confirm the first line matches the names below.
-- If your file uses different spelling (e.g. Facility_Name vs Facility_Na), rename
-- either the CSV headers or the column names here before importing.

create table if not exists public.facility_rooms (
  id bigint generated by default as identity primary key,
  "Facility_ID" text,
  "Facility_Na" text,
  "Designed_F" text,
  "Field_Roon" text,
  "Room_As_Is" text,
  "Room_Cate" text,
  "Room_Type" text,
  "Room_As_Used" text,
  "Area" numeric
);

create index if not exists facility_rooms_facility_id_idx
  on public.facility_rooms ("Facility_ID");

alter table public.facility_rooms enable row level security;

-- Only approved dashboard users can read facility data
drop policy if exists "Approved users can read facility_rooms" on public.facility_rooms;
create policy "Approved users can read facility_rooms"
  on public.facility_rooms for select
  using (public.is_approved());

-- Admin can manage data (optional — for imports via dashboard as postgres role)
drop policy if exists "Admin can manage facility_rooms" on public.facility_rooms;
create policy "Admin can manage facility_rooms"
  on public.facility_rooms for all
  using ((auth.jwt() ->> 'email') = 'k12strategies@perkinseastman.com')
  with check ((auth.jwt() ->> 'email') = 'k12strategies@perkinseastman.com');
